# Generated by Django 5.0.1 on 2024-12-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='remarks',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Only for transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiveed_transfer', to='customer.user'),
        ),
    ]
