# Generated by Django 5.0.1 on 2024-12-16 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_accounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='middlename',
            new_name='middle_name',
        ),
    ]
