# Generated by Django 5.0.1 on 2024-12-16 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_firstname_accounts_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='date_created',
            new_name='created_at',
        ),
    ]
